### ISSUE TITLE
All links under Commands and Reports link to https://nagios.web-ster.com/

### ISSUE THREAD

**Issue by akglaza** [scottchiefbaker/nagiosvshell#2]
Installed vShell to play around with real quick and noticed that after getting into vshell, all of the links under the Commands and Reports navigation menu in the header link to https://nagios.web-ster.com/ instead of my local host.

**Comment by scottchiefbaker** [comment]
Aha good catch. I had hardcoded references to my testing domain. That should be corrected in 610972e now.

**Comment by scottchiefbaker** [comment]
Please test and confirm and then we can close this issue.

**Comment by akglaza** [comment]
Tested, looks good.
